# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='id_Produit',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='id_Employer',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='id_Employer',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
