# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_remove_client_siren'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={},
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='id_Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='ligne',
            old_name='id_Produit',
            new_name='produit',
        ),
    ]
