# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_auto_20181002_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='id_Produit',
        ),
        migrations.AddField(
            model_name='ligne',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facture.Facture'),
        ),
    ]
