# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_remove_facture_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('cover', models.ImageField(upload_to=None)),
            ],
            options={
                'ordering': ('cover', 'first_name', 'last_name', 'email', 'address'),
            },
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
        migrations.AlterField(
            model_name='ligne',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facture.Devis'),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
