# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0007_auto_20181003_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name_plural': 'Devis'},
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='plop', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zipcode',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
