# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0009_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='etat',
            field=models.CharField(choices=[('PAID', 'Paid'), ('REVIVE', 'Revive'), ('WAITING', 'Waiting')], default='WAITING', max_length=20),
        ),
    ]
