# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_devis_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(choices=[('REVIVE', 'A relancer'), ('PAID', 'Payer'), ('WAITING', 'En attente')], default='WAITING', max_length=20),
        ),
    ]
